import type { Metadata } from "next";
import "@/styles/globals.scss";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-CN"
    >
      <body className="min-h-screen flex flex-col relative">
        <Image
          src="/bg.jpg"
          alt="bg"
          fill={true}
          loading="eager"
          className="absolute top-0 left-0 w-full h-full object-cover"
        />
        {children}
      </body>
    </html>
  );
}
